#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	rt_entry_t *entry1 = NULL;
	rt_entry_t *entry2 = NULL;
	rt_entry_t *max_entry = NULL;
	u32 max_mask = 0;
	list_for_each_entry_safe(entry1, entry2, &rtable, list)
	{
		if((dst & entry1->mask) == (entry1->dest & entry1->mask) && (entry1->mask > max_mask))
		{
			max_mask = entry1->mask;
			max_entry = entry1;
		}
	}
	
	//fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	return max_entry;
}

// send IP packet
//
// Different from ip_forward_packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	struct iphdr *ip = packet_to_ip_hdr(packet);
	u32 ip_dst = ntohl(ip->daddr);
	rt_entry_t *rt_entry = longest_prefix_match(ip_dst);
	u32 next_hop = entry->gw;
    if (!next_hop)
	{
		next_hop = dst;
	}
    struct ether_header *eh = (struct ether_header *)packet;
    eh->ether_type = ntohs(ETH_P_IP);
    memcpy(eh->ether_shost, entry->iface->mac, ETH_ALEN);
	
	iface_send_packet_by_arp(rt_entry->iface, next_hop, packet, len);
	//fprintf(stderr, "TODO: send ip packet.\n");
}
